[build-system]
requires = ["flit_core >=4.0.2,<5"]
build-backend = "flit_core.buildapi"

[project]
name = "aiorun"
authors = [
    {name = "Caleb Hattingh", email = "caleb.hattingh@gmail.com"},
]
description = "Boilerplate for asyncio applications"
readme = "README.rst"
requires-python = ">=3.7"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[project.urls]
Home = "https://github.com/cjrh/aiorun"
